# Name: Godfrey maina
# RegNo: 19/03627
# Numpy assignment

## Creating a numpy array

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## creating a 0-D Arrays

In [2]:
arr = np.array(42)

print(arr)


42


## creating a 1-D Arrays

In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


## creating a 2-D Arrays

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


## creating a 3-D Arrays

In [5]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check Number of Dimensions

In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr.ndim)

3


## Slicing arrays

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


## Slicing leaving the start index arrays

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:5])

[1 2 3 4 5]


## Negative Slicing

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


## slicing using step

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


## slicing leaving the start and the end index

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


## copying a numy array

In [12]:
arr = np.array([1, 2, 3, 4, 5])
newArr = arr.copy()
arr[0] = 42

print(arr)
print(newArr)

[42  2  3  4  5]
[1 2 3 4 5]


## Viewing a numpy array

In [13]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


## cheking the owner of the numy array

the copy returns None the view return the original array

In [14]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## The shape of a numpy array

this is the number of element in each array

In [15]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


## Iterating  a simple numpy array

In [16]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


## Iterating  a complex numpy array

In [17]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


## Joining NumPy Arrays

In [18]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


## Splitting a numy array

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


## Searching numpy Arrays

the where method returns the index of the element that much the specified condition

In [21]:

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


## Sorting Arrays

We use the sort() to sort a numy array

This method returns a copy of the array, leaving the original array unchanged.

In [23]:
arr = np.array([3, 2, 0, 1])

In [26]:
np.sort(arr)

array([0, 1, 2, 3])

## Sorting a 2-D Array
If you use the sort() method on a 2-D array, both arrays will be sorted:

In [27]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

In [28]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


Create a filter array that will return only values higher than 42:

In [29]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


## Generate Random Number
NumPy offers the random module to work with random numbers.

In [36]:
from numpy import random

x = random.randint(100)

print(x)

91


##Generate Random Float
The random module's rand() method returns a random float between 0 and 1.

In [38]:
x = random.rand()

print(x)

0.801172236535546


In [39]:
x = random.rand()

print(x)

0.9231471597185082


## Generate Random Array
In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

## Integers
The randint() method takes a size parameter where you can specify the shape of an array.

In [40]:
x=random.randint(100, size=(5))

print(x)

[78 40 45 35 79]


Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

In [41]:
x = random.randint(100, size=(3, 5))

print(x)

[[11 97 56 23 78]
 [90 47 82 14 84]
 [43 13 21 73 78]]


## Generate Random Number From Array
The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [42]:
x = random.choice([3, 5, 7, 9])

print(x)

9
